version: "3.9" 
services:
  frontend:
    image: frontend
    ports:
      - "5001:5000"
    links:
      - backend
    environment:
      - BACKEND_LOCATION=http://backend:5000
  backend:
    image: backend
    ports:
      - "5000:5000" 
